var alphabetA = document.createElement("SCRIPT");var aaSrc = document.createAttribute("src");aaSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaA.js";alphabetA.setAttributeNode(aaSrc);
var alphabetB = document.createElement("SCRIPT");var abSrc = document.createAttribute("src");abSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaB.js";alphabetB.setAttributeNode(abSrc);
var alphabetC = document.createElement("SCRIPT");var acSrc = document.createAttribute("src");acSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaC.js";alphabetC.setAttributeNode(acSrc);
var alphabetD = document.createElement("SCRIPT");var adSrc = document.createAttribute("src");adSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaD.js";alphabetD.setAttributeNode(adSrc);
var alphabetE = document.createElement("SCRIPT");var aeSrc = document.createAttribute("src");aeSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaE.js";alphabetE.setAttributeNode(aeSrc);
var alphabetF = document.createElement("SCRIPT");var afSrc = document.createAttribute("src");afSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaF.js";alphabetF.setAttributeNode(afSrc);
var alphabetG = document.createElement("SCRIPT");var agSrc = document.createAttribute("src");agSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaG.js";alphabetG.setAttributeNode(agSrc);
var alphabetH = document.createElement("SCRIPT");var ahSrc = document.createAttribute("src");ahSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaH.js";alphabetH.setAttributeNode(ahSrc);
var alphabetI = document.createElement("SCRIPT");var aiSrc = document.createAttribute("src");aiSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaI.js";alphabetI.setAttributeNode(aiSrc);
var alphabetJ = document.createElement("SCRIPT");var ajSrc = document.createAttribute("src");ajSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaJ.js";alphabetJ.setAttributeNode(ajSrc);
var alphabetK = document.createElement("SCRIPT");var akSrc = document.createAttribute("src");akSrc.value = "http://software.remakenow.us/JavaScript/LangaugeDiction/English/Alphabet/wordAlphaK.js";alphabetK.setAttributeNode(akSrc);
var alphabetL = document.createElement("SCRIPT");var alSrc = document.createAttribute("src");alSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaL.js";alphabetL.setAttributeNode(alSrc);
var alphabetM = document.createElement("SCRIPT");var amSrc = document.createAttribute("src");amSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaM.js";alphabetM.setAttributeNode(amSrc);
var alphabetN = document.createElement("SCRIPT");var anSrc = document.createAttribute("src");anSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaN.js";alphabetN.setAttributeNode(anSrc);
var alphabetO = document.createElement("SRCIPT");var aoSrc = document.createAttribute("src");aoSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaO.js";alphabetO.setAttributeNode(aoSrc);
var alphabetP = document.createElement("SCRIPT");var apSrc = document.createAttribute("src");apSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaP.js";alphabetP.setAttributeNode(apSrc);
var alphabetQ = document.createElement("SCRIPT");var aqSrc = document.createAttribute("src");aqSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaQ.js";alphabetQ.setAttributeNode(aqSrc);
var alphabetR = document.createElement("SRCIPT");var arSrc = document.createAttribute("src");arSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaR.js";alphabetR.setAttributeNode(arSrc);
var alphabetS = document.createElement("SCRIPT");var asSrc = document.createAttribute("src");asSrc.value = "http://software.remakenow.us/JavaScript/LangaugeDiction/English/Alphabet/wordAlphaS.js";alphabetS.setAttributeNode(asSrc);
var alphabetT = document.createElement("SCRIPT");var atSrc = document.createAttribute("src");atSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaT.js";alphabetT.setAttributeNode(atSRc);
var alphabetU = document.createElement("SCRIPT");var auSrc = document.createAttribute("src");auSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaU.js";alphabetU.setAttributeNode(auSrc);
var alphabetV = document.createElement("SCRIPT");var avSrc = document.createAttribute("src");avSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaV.js";alphabetV.setAttributeNode(avSrc);
var alphabetW = document.createElement("SCRIPT");var awSrc = document.createAttribute("src");awSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaW.js";alphabetW.setAttributeNode(awSrc);
var alphabetX = document.createElement("SCRIPT");var axSrc = document.createAttribute("src");axSrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/Englsih/Alphabet/wordAlphaX.js";alphabetX.setAttributeNode(axSrc);
var alphabetY = document.createElement("SCRIPT");var aySrc = document.createAttribute("src");aySrc.value = "http://software.remakenow.us/JavaScript/LanguageDiction/English/Alphabet/wordAlphaY.js";alphabetY.setAttributeNode(aySrc);
var alphabetZ = document.createElement("SRCIPT");var azSrc = document.createAttribute("src");azSrc.value = "http://software.remakenow.us/JavaScript/LangaugeDiction/English/Alphabet/wordAlphaZ.js";alphabetZ.setAttributeNode(azSrc);
function alphabet(){
 document.getElementByTagName("DIV")[1].appendChild(alphabetA);
 document.getElementByTagName("DIV")[1].appendChild(alphabetB);
 document.getElementByTagName("DIV")[1].appendChild(alphabetC);
 document.getElementByTagName("DIV")[1].appendChild(alphabetD);
 document.getElementByTagName("DIV")[1].appendChild(alphabetE);
 document.getElementByTagName("DIV")[1].appendChild(alphabetF);
 document.getElementByTagName("DIV")[1].appendChild(alphabetG);
 document.getElementByTagName("DIV")[1].appendChild(alphabetH);
 document.getElementByTagName("DIV")[1].appendChild(alphabetI);
 document.getElementByTagName("DIV")[1].appendChild(alphabetJ);
 document.getElementByTagName("DIV")[1].appendChild(alphabetK);
 document.getElementByTagName("DIV")[1].appendChild(alphabetL);
 document.getElementByTagName("DIV")[1].appendChild(alphabetM);
 document.getElementByTagName("DIV")[1].appendChild(alphabetN);
 document.getElementByTagName("DIV")[1].appendChild(alphabetO);
 document.getElementByTagName("DIV")[1].appendChild(alphabetP);
 document.getElementByTagName("DIV")[1].appendChild(alphabetQ);
 document.getElementByTagName("DIV")[1].appendChild(alphabetR);
 document.getElementByTagName("DIV")[1].appendChild(alphabetS);
 document.getElementByTagName("DIV")[1].appendChild(alphabetT);
 document.getElementByTagName("DIV")[1].appendChild(alphabetU);
 document.getElementByTagName("DIV")[1].appendChild(alphabetV);
 document.getElementByTagName("DIV")[1].appendChild(alphabetW);
 document.getElementByTagName("DIV")[1].appendChild(alphabetX);
 document.getElementByTagName("DIV")[1].appendCHild(alphabetY);
 document.getElementByTagName("DIV")[1].appendCHIld(alphabetZ);
}
