var a;var b;var c;var d;var e;var f;var g;var h;var i;var j;var k;var l;var m;var n;var o;var p;var q;var r;var s;var t;var u;var v;var w;var x;var y;var z;
a = "b";b = "c";c = "d";d = "e";e = "f";f = "g";g = "h";h = "i";i = "j";j = "k";k = "l";l = "m";m = "n";n = "o";o = "p";p = "q";q = "r";r = "s";s = "t";t = "u";u = "v";v = "w";w = "x";x = "y";y = "z";z = "a";
var A;var B;var C;var D;var E;var F;var G;var H;var I;var J;var K;var L;var M;var N;var O;var P;var Q;var R;var S;var T;var U;var V;var W;var X;var Y;var Z;
A = "B";B = "C";C = "D";D = "E";E = "F";F = "G";G = "H";H = "I";I = "J";J = "K";K = "L";L = "M";M = "N";N = "O";O = "P";P = "Q";Q = "R";R = "S";S = "T";T = "U";U = "V";V = "W";W = "X";X = "Y";Y = "Z";Z = "A";
var num = 0;var dataArray = new Array();
function layerOne(text){
 var dat = text;
 for(var i = 0;i<dat.length){
  if(num==0){
   if(dat[i]=="a"){
   }else{
    if(dat[i]=="b"){
    }else{
     if(dat[i]=="c"){
     }else{
      if(dat[i]=="d"){
      }else{
       if(dat[i]=="e"){
       }else{
        if(dat[i]=="f"){
        }else{
         if(dat[i]=="g"){
         }else{
          if(dat[i]=="h"){
          }else{
           if(dat[i]=="i"){
           }else{
            if(dat[i]=="j"){
            }else{
             if(dat[i]=="k"){
             }else{
              if(dat[i]=="l"){
              }else{
               if(dat[i]=="m"){
               }else{
                if(dat[i]=="n"){
                }else{
                 if(dat[i]=="o"){
                 }else{
                  if(dat[i]=="p"){
                  }else{
                   if(dat[i]=="q"){
                   }else{
                    if(dat[i]=="r"){
                    }else{
                     if(dat[i]=="s"){
                     }else{
                      if(dat[i]=="t"){
                      }else{
                       if(dat[i]=="u"){
                       }else{
                        if(dat[i]=="v"){
                        }else{
                         if(dat[i]=="w"){
                         }else{
                          if(dat[i]=="x"){
                          }else{
                           if(dat[i]=="y"){
                           }else{
                            if(dat[i]=="z"){
                            }else{
                             if(dat[i]=="A"){
                             }else{
                              if(dat[i]=="B"){
                              }else{
                               if(dat[i]=="C"){
                               }else{
                                if(dat[i]=="D"){
                                }else{
                                 if(dat[i]=="E"){
                                 }else{
                                  if(dat[i]=="F"){
                                  }else{
                                   if(dat[i]=="G"){
                                   }else{
                                    if(dat[i]=="H"){
                                    }
                                   }
                                  }
                                 }
                                }
                               }
                              }
                             }
                            }
                           }
                          }
                         }
                        }
                       }
                      }
                     }
                    }
                   }
                  }
                 }
                }
               }
              }
             }
            }
           }
          }
         }
        }
       }
      }
     }
    }
   }
  }else{
  }
 }
}
